# Generated by Django 5.0.7 on 2024-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('userId', models.IntegerField(max_length=400)),
                ('cretaedAt', models.DateField()),
            ],
        ),
    ]
