# Generated by Django 5.0.7 on 2024-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='videos/')),
                ('userId', models.IntegerField()),
                ('createdAt', models.DateField()),
            ],
        ),
    ]
