# Generated by Django 5.0.7 on 2024-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
