# Generated by Django 5.0.7 on 2024-07-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videofiles_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='path',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
